### PR TITLE
Fixing bug: Move comments.

### LINKED ISSUE #68: Fix documentation of the enum class
all descriptions of enum items should be located near an enum item
**Example**
```cpp
/**
 * @brief The Extensinon enum File extensions for signature.
 */
enum Extensinon {
    /// The CPP file is a source code file written in C++.
    CPP,
};
```

### PR DESCRIPTION
**Pull request by IgorekLoschinin**
fix #68  Move comments.

### CODE REVIEW

File: src/CopyrighFixer/CopyrighFixer/ifilemanager.h [hunk 1]
```diff
@@ -16,23 +16,38 @@ namespace CopyrighFixer {
...
- * @param TXT The source code is written in the txt file in CMake language.
- * @param Py  The py file contains the source code in python.
+ * @param
+ * @param
+ * @param H
+ * @param CC
+ * @param QML
+ * @param PRO
+ * @param TXT
+ * @param Py
```
Comment (EndrII) [inline src/CopyrighFixer/CopyrighFixer/ifilemanager.h]:
```suggestion
```

**Review by EndrII — CHANGES_REQUESTED** [review]

**Review by EndrII — APPROVED** [review]
